#!/usr/bin/env python3
"""Write src/XivPiano.Core/Pandora/BlowfishTables.cs: Blowfish's initial P-array and
S-boxes, which are by definition the hexadecimal digits of pi's fractional part
(P1 = 0x243F6A88, ...). Computed here with Machin's formula, not copied from anywhere."""
import pathlib

WORDS = 18 + 4 * 256
BITS = WORDS * 32 + 64  # guard bits


def arctan_inv(x, one):
    """arctan(1/x) * one, by its Taylor series in integers."""
    total = term = one // x
    x2, n, sign = x * x, 3, -1
    while term:
        term //= x2
        total += sign * (term // n)
        n, sign = n + 2, -sign
    return total


one = 1 << BITS
pi = 4 * (4 * arctan_inv(5, one) - arctan_inv(239, one))
frac = pi - (3 << BITS)  # the fractional part, as a BITS-bit fixed-point number
words = [(frac >> (BITS - 32 * (i + 1))) & 0xFFFFFFFF for i in range(WORDS)]
assert words[0] == 0x243F6A88 and words[17] == 0x8979FB1B, "P-array check"
assert words[18] == 0xD1310BA6, "S-box check"


def block(ws):
    lines = []
    for i in range(0, len(ws), 8):
        lines.append("        " + ", ".join(f"0x{w:08X}" for w in ws[i:i + 8]) + ",")
    return "\n".join(lines)


out = f"""// Generated by tools/blowfish-tables.py: Blowfish's initial P-array and S-boxes are the
// hexadecimal digits of pi's fractional part. Do not edit; re-run the tool.
namespace XivPiano.Core.Pandora;

internal static class BlowfishTables
{{
    internal static readonly uint[] P =
    [
{block(words[:18])}
    ];

    /// <summary>The four S-boxes, one after another (4 x 256).</summary>
    internal static readonly uint[] S =
    [
{block(words[18:])}
    ];
}}
"""
path = pathlib.Path(__file__).resolve().parent.parent / "src/XivPiano.Core/Pandora/BlowfishTables.cs"
path.write_text(out)
print(f"wrote {path.name}: {WORDS} words")
